ResoureceGroup = "VMRG"
RGLocation     = "EastUS"
#VM_Name = "WebVM"
#VM_Size     = "Standard_B2s_v2"
VM_Image_ID = "/subscriptions/b6623f02-e260-46db-a964-6b0d9704c794/resourceGroups/KamakshiRG/providers/Microsoft.Compute/galleries/Windows_Image_Gallery/images/WindowsImage-Webapp/versions/1.0.0"
